Vagrant.configure("2") do |config|
  config.vm.define "kubmaster" do |kub|
    kub.vm.box = "bento/ubuntu-16.04"
    kub.vm.hostname = 'kubmaster'
    kub.vm.provision :docker
    kub.vm.box_url = "https://vagrantcloud.com/bento/boxes/ubuntu-16.04"

    kub.vm.network :private_network, ip: "192.168.56.101"

    kub.vm.provider :virtualbox do |v|
      v.memory = 2048
      v.name = "kubmaster"
      v.cpus = 2
    end
  end

  config.vm.define "kubnode" do |kub|
    kub.vm.box = "bento/ubuntu-16.04"
    kub.vm.hostname = 'kubnode'
    kub.vm.provision :docker
    kub.vm.box_url = "https://vagrantcloud.com/bento/boxes/ubuntu-16.04"

    kub.vm.network :private_network, ip: "192.168.56.102"

    kub.vm.provider :virtualbox do |v|
      v.memory = 2048
      v.name = "kubnode"
      v.cpus = 2
    end
  end
end
