# Reduce logging level to make sure the application works with SAM local
# https://github.com/awslabs/aws-serverless-java-container/issues/134
spring:
  mvc:
    servlet:
      path: /api/v1/vote

logging:
  level:
    root: info